#!/usr/bin/env python3
"""Generate the kintsugi crack/seam mask tokens (§5.3) for themes/sumi_house.yaml.

Geometry follows the approved prototype (Concepts/sumi-house-mock.html, `--crack`): a
long vein with gentle wobble running the full length of an edge, a wide faint glow, a
thin bright core and a few short side-branches. The masks are white-on-transparent SVGs;
the copper comes from the theme tokens (a gradient behind the mask), so one geometry
serves both modes.

Tokens written:
  sumi-crack       the horizontal crack as a bare url(...) — used under the header
  sumi-seam-1..5   full mask shorthands (url + position / size + no-repeat) for cards

    python3 scripts/gen_seams.py    # prints the token lines; paste into the theme

Standard library only.
"""
from __future__ import annotations

import urllib.parse

# Horizontal cracks live in a 600×14 box (like the prototype), vertical ones in 14×600.
# The vein runs ~3.5 units from the outer edge, so with `inset: -1px` on the pseudo-element
# it sits 2–3px inside the card border, as the prototype's does under its header.
H1 = ("M0 4 L60 2.5 120 5 180 1.5 240 4 300 1 360 4.5 420 2 480 5.5 540 3 600 4",
      "M180 1.5 L198 7 M360 4.5 L376 9.5 M480 5.5 L494 0.5")
H2 = ("M0 3 L45 5 105 2 165 4.5 225 1.5 285 4 345 2 405 5 465 2.5 525 4.5 600 3",
      "M105 2 L118 8 M285 4 L300 9 M465 2.5 L452 8")
H3 = ("M0 4.5 L70 2 130 4 190 1 250 3.5 310 5 370 2 430 4.5 490 1.5 550 4 600 2.5",
      "M190 1 L206 6.5 M430 4.5 L446 10 M550 4 L538 9")
V1 = ("M4 0 L2.5 60 5 120 1.5 180 4 240 1 300 4.5 360 2 420 5.5 480 3 540 4 600",
      "M1.5 180 L7 198 M4.5 360 L9.5 376 M5.5 480 L0.5 494")
V2 = ("M3 0 L5 45 2 105 4.5 165 1.5 225 4 285 2 345 5 405 2.5 465 4.5 525 3 600",
      "M2 105 L8 118 M4 285 L9 300 M2.5 465 L8 452")

# For bottom / right edges the vein must hug the far side of the box: mirror y (or x).
def mirror(path: str, size: float = 14.0, axis: str = "y") -> str:
    out = []
    for tok in path.replace("L", " L ").replace("M", " M ").split():
        if tok in ("M", "L"):
            out.append(tok)
            continue
        out.append(tok)
    # pairs: x y x y …  — mirror the chosen coordinate
    res, coords, cmds = [], [], []
    for tok in out:
        if tok in ("M", "L"):
            res.append(tok)
        else:
            coords.append(float(tok))
            if len(coords) == 2:
                x, y = coords
                if axis == "y":
                    y = size - y
                else:
                    x = size - x
                res.append(f"{x:g} {y:g}")
                coords = []
    return " ".join(res)

SEAMS = [
    ("sumi-seam-1", "h", H1, "left top", "100% 14px", "top edge, full length (default)"),
    ("sumi-seam-2", "h", (mirror(H2[0]), mirror(H2[1])), "left bottom", "100% 14px", "bottom edge, full length"),
    ("sumi-seam-3", "v", V1, "left top", "14px 100%", "left edge, full length"),
    ("sumi-seam-4", "v", (mirror(V2[0], axis="x"), mirror(V2[1], axis="x")), "right top", "14px 100%", "right edge, full length"),
    ("sumi-seam-5", "h", H3, "left top", "62% 14px", "top edge, entering from the left, 62%"),
]

GLOW = (3.5, 0.16)     # wide, faint halo
CORE = (1.2, 1.0)      # the vein itself
BRANCH = (0.8, 0.85)   # short side-veins


def svg(orientation: str, paths: tuple[str, str]) -> str:
    w, h = ("600", "14") if orientation == "h" else ("14", "600")
    main, branches = paths
    def stroke(d, width, op):
        return (f"<path d='{d}' fill='none' stroke='#fff' stroke-opacity='{op}' "
                f"stroke-width='{width}' stroke-linejoin='round' stroke-linecap='round'/>")
    body = stroke(main, *GLOW) + stroke(main, *CORE) + stroke(branches, *BRANCH)
    return (f"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 {w} {h}' "
            f"preserveAspectRatio='none'>{body}</svg>")


def data_uri(markup: str) -> str:
    return "data:image/svg+xml," + urllib.parse.quote(markup, safe="=/:,.-")


def main() -> None:
    print("  # §5.3 kintsugi — CSS masks. GENERATED by scripts/gen_seams.py (geometry from the prototype).")
    print("  # sumi-crack is the bare horizontal vein (header); sumi-seam-N are card shorthands —")
    print("  # a card picks one with `--sumi-seam: var(--sumi-seam-N)`; the default is seam 1.")
    print(f"  sumi-crack: 'url(\"{data_uri(svg('h', H1))}\")'")
    for name, orient, paths, pos, size, comment in SEAMS:
        print(f"  # {comment}")
        print(f"  {name}: 'url(\"{data_uri(svg(orient, paths))}\") {pos} / {size} no-repeat'")


if __name__ == "__main__":
    main()
