#!/usr/bin/env python3
"""Generate docs/tokens.md — the token reference — from themes/sumi_house.yaml.

    python3 scripts/gen_tokens_doc.py

The theme file is the single source of truth; do not edit docs/tokens.md by hand.
Standard library only.
"""
from __future__ import annotations

import io
import sys
from contextlib import redirect_stdout
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import contrast  # noqa: E402
from _themeyaml import ROOT, load_theme  # noqa: E402

OUT = ROOT / "docs" / "tokens.md"


def swatch(value: str) -> str:
    return f"`{value}`"


def main() -> int:
    name, theme = load_theme()
    dark, light = theme["modes"]["dark"], theme["modes"]["light"]
    fixed = {k: v for k, v in theme.items() if k.startswith("sumi-") and k != "modes"}

    lines: list[str] = []
    lines.append(f"# {name} — token reference")
    lines.append("")
    lines.append("GENERATED by `scripts/gen_tokens_doc.py` from `themes/sumi_house.yaml`. Do not edit by hand.")
    lines.append("")
    lines.append("In YAML the tokens are written without the leading `--`; in CSS (card-mod, custom cards) reference them as `var(--sumi-…)`.")
    lines.append("")
    lines.append("## Per-mode tokens")
    lines.append("")
    lines.append("| Token | Dark (墨) | Light (washi) |")
    lines.append("|---|---|---|")
    for key in dark:
        lines.append(f"| `{key}` | {swatch(str(dark[key]))} | {swatch(str(light.get(key, '')))} |")
    lines.append("")
    lines.append("## Mode-independent tokens")
    lines.append("")
    lines.append("| Token | Value |")
    lines.append("|---|---|")
    for key, value in fixed.items():
        v = str(value)
        if len(v) > 90:
            v = v[:87] + "…"
        lines.append(f"| `{key}` | `{v}` |")
    lines.append("")
    lines.append("## Contrast (WCAG 2.1, against `sumi-surface` in each mode)")
    lines.append("")
    buf = io.StringIO()
    with redirect_stdout(buf):
        status = contrast.run(markdown=True)
    lines.append(buf.getvalue().rstrip("\n"))
    lines.append("")
    lines.append("Result: " + ("**PASS** — every enforced token clears its minimum." if status == 0 else "**FAIL** — see `python3 scripts/contrast.py`."))
    lines.append("")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
