#!/usr/bin/env python3
"""Local preview of the Sumi House theme — no Home Assistant required.

Builds two stylesheets from themes/sumi_house.yaml and serves the repo so that
preview/index.html renders with the *real* theme assets:

  preview/theme.css    tokens + HA variable map on <html>, per mode — exactly how HA applies
                       a theme (as custom properties on the root element)
  preview/cardmod.css  the card-mod-* blocks, verbatim (only `:host` in card-mod-root is
                       rewritten to `hui-root`, the element card-mod would inject into)

The server maps /local/… → www/… like Home Assistant does, so the genuine font loader
module (/local/sumi-house/sumi-fonts.js) and the woff2 files load unchanged. Both CSS
files are rebuilt on every request, so edit the YAML and refresh.

    python3 scripts/preview.py              # build, serve on http://localhost:8765, open browser
    python3 scripts/preview.py --port 9000
    python3 scripts/preview.py --no-open
    python3 scripts/preview.py --build-only

Fonts are the reason for the server: Chrome refuses web fonts over file://.
Standard library only.
"""
from __future__ import annotations

import argparse
import http.server
import sys
import webbrowser
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _themeyaml import ROOT, load_theme  # noqa: E402

PREVIEW = ROOT / "preview"
THEME_CSS = PREVIEW / "theme.css"
CARDMOD_CSS = PREVIEW / "cardmod.css"


def _decl(key: str, value) -> str:
    return f"  --{key}: {str(value).strip()};"


def build() -> None:
    name, theme = load_theme()
    modes = theme["modes"]
    top = {k: v for k, v in theme.items() if k != "modes" and not k.startswith("card-mod-")}

    css = [f"/* {name} — GENERATED by scripts/preview.py from themes/sumi_house.yaml. Do not edit. */", "html {"]
    css += [_decl(k, v) for k, v in top.items()]
    css.append("}")
    for mode in ("dark", "light"):
        css.append(f'html[data-mode="{mode}"] {{')
        css += [_decl(k, v) for k, v in modes[mode].items()]
        css.append("}")
    css.append('html[data-mode="dark"] { color-scheme: dark; }')
    css.append('html[data-mode="light"] { color-scheme: light; }')
    THEME_CSS.write_text("\n".join(css) + "\n", encoding="utf-8")

    cm = [f"/* {name} — card-mod blocks, GENERATED by scripts/preview.py. Do not edit. */"]
    order = ["card-mod-root", "card-mod-view", "card-mod-card", "card-mod-sidebar", "card-mod-more-info"]
    for key in order + [k for k in theme if k.startswith("card-mod-") and k not in order and k != "card-mod-theme"]:
        block = theme.get(key)
        if not isinstance(block, str):
            continue
        if key == "card-mod-root":
            # card-mod injects this into hui-root's shadow root, where `.header` is only the
            # toolbar. The preview has no shadow DOM, so scope it to avoid matching card headers.
            block = block.replace(":host", "hui-root").replace(".header", "hui-root > .header")
        cm.append(f"\n/* ── {key} ── */")
        cm.append(block.rstrip("\n"))
    CARDMOD_CSS.write_text("\n".join(cm) + "\n", encoding="utf-8")


class Handler(http.server.SimpleHTTPRequestHandler):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=str(ROOT), **kwargs)

    def do_GET(self) -> None:
        clean = self.path.split("?", 1)[0]
        if clean in ("", "/", "/preview", "/preview/"):
            query = self.path[len(clean):]
            self.send_response(302)
            self.send_header("Location", "/preview/index.html" + query)
            self.end_headers()
            return
        super().do_GET()

    def translate_path(self, path: str) -> str:
        clean = path.split("?", 1)[0].split("#", 1)[0]
        if clean.startswith("/local/"):
            clean = "/www/" + clean[len("/local/"):]
        if clean in ("/preview/theme.css", "/preview/cardmod.css"):
            build()
        return super().translate_path(clean)

    def end_headers(self) -> None:
        self.send_header("Cache-Control", "no-store")
        super().end_headers()

    def log_message(self, fmt, *args):  # quieter log: only errors
        if args and str(args[1]).startswith(("4", "5")):
            super().log_message(fmt, *args)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--port", type=int, default=8765)
    ap.add_argument("--no-open", action="store_true")
    ap.add_argument("--build-only", action="store_true")
    args = ap.parse_args()

    build()
    print(f"built {THEME_CSS.relative_to(ROOT)} and {CARDMOD_CSS.relative_to(ROOT)}")
    if args.build_only:
        return 0

    url = f"http://localhost:{args.port}/preview/index.html"
    server = http.server.ThreadingHTTPServer(("127.0.0.1", args.port), Handler)
    print(f"serving {url}  (Ctrl-C to stop)")
    if not args.no_open:
        webbrowser.open(url)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    return 0


if __name__ == "__main__":
    sys.exit(main())
